### ISSUE TITLE
ERROS WHEN CLIPBOARD IS INITIALLY EMPTY

### ISSUE THREAD

**Issue by msscaroso** [msscaroso/youtube-ctrl-c-downloader#1]
If the clipboard is initially empty, the program will raise an error.

**Comment by yarodevuci** [comment]
how does it work? why is it in Spanish?!!

**Comment by MrDudis** [comment]
> how does it work? why is it in Spanish?!!

it should download every video link that you copied, but it doenst seem to work
btw its not spanish, its portuguese.
